<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DB configuration</title>
</head>
<body>
    <!-- <b>dbconfig.phtml in configdb in view... </b> -->
    <!-- <br> -->
    <p>App name is : <b> <?= $appName; ?></b> </p>
    <p>App version is : <b><?= $appVersion; ?></b> </p>

    <p>Host name is : <b> <?= $host; ?></b> </p>
    <p>Username is : <b> <?= $username; ?></b> </p>
    <p>DBname is : <b> <?= $dbname; ?></b> </p>



</body>
</html>